version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install rsync
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - run: rsync -avz --delete -e "ssh -p ${DEPLOY_PORT} -o StrictHostKeyChecking=no" ~/repo/dist/ ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_PATH}
